name: Test Python Package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies from requirements_full.txt
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_full.txt

      - name: Install local do-mpc in editable mode
        run: |
          # Make sure we install the version from this repo, not PyPI.
          pip uninstall -y do-mpc   # (optional but ensures no conflict)
          pip install -e .
      - name: Test
        run: |
          cd testing
          python -m unittest